#!/usr/bin/env python3
"""Assembler: proto-emu assembly text -> 24-bit instruction words / $readmemh hex.

    python3 tools/asm.py prog.asm                 # hex to stdout
    python3 tools/asm.py prog.asm -o prog.hex
    python3 tools/asm.py -d prog.hex              # disassemble

Syntax (one instruction per line; `;` or `//` start a comment):

    .side_set N                  side-set bit count (0-2), before any instruction
    label:                       may share a line with an instruction
    jmp [cond] target            cond: !x  x--  !y  y--  x!=y  pin  !osre
    wait POL pin|gpio|timer|flag INDEX
    in   pins|x|y|zeros|isr|osr, COUNT        COUNT 1-32
    out  pins|x|y|null|pindirs|pc, COUNT      COUNT 1-32
    push [iffull]  [block|noblock]           default block
    pull [ifempty] [block|noblock]           default block
    set  pins|x|y|pindirs, VALUE             VALUE 0-255
    .word VALUE                  raw instruction; must pass the reserved-bit check

Any instruction may end with `side S` (required when .side_set > 0) and then `[DELAY]`.
Encodings come from tools/isa.py, which reads src/proto_emu_pkg.vh.
"""

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import isa


class AsmError(Exception):
    pass


@dataclass
class Program:
    words: list
    side_set_count: int = 0
    labels: dict = field(default_factory=dict)
    source: list = field(default_factory=list)  # source text per word, for listings

    def image(self):
        """Full PROG_DEPTH memory image; unused addresses are None (uninitialized)."""
        return self.words + [None] * (isa.PROG_DEPTH - len(self.words))

    def to_hex(self, name="program"):
        lines = [f"// Generated by tools/asm.py from {name} -- do not edit by hand.",
                 f"// side_set = {self.side_set_count}"]
        for addr, (word, src) in enumerate(zip(self.words, self.source)):
            lines.append(f"{word:06X} // {addr:3d}: {src}")
        return "\n".join(lines) + "\n"


_COMMENT_RE = re.compile(r"(;|//).*$")
_LABEL_RE = re.compile(r"^([A-Za-z_]\w*)\s*:\s*(.*)$")
_DELAY_RE = re.compile(r"\[\s*([^\]]+?)\s*\]\s*$")
_SIDE_RE = re.compile(r"\bside\s+(\S+)\s*$", re.IGNORECASE)


def _int(text, what):
    try:
        return int(text, 0)
    except ValueError:
        raise AsmError(f"expected a number for {what}, got {text!r}") from None


def _ranged(text, what, lo, hi):
    value = _int(text, what)
    if not lo <= value <= hi:
        raise AsmError(f"{what} {value} out of range {lo}-{hi}")
    return value


def _select(name, table, what):
    key = name.upper()
    if key not in table:
        legal = ", ".join(k.lower() for k in table)
        raise AsmError(f"unknown {what} {name!r} (expected one of: {legal})")
    return table[key]


def _count(text):
    # 32 encodes as 0 in the 5-bit count field
    return _ranged(text, "bit count", 1, 32) % 32


def _operands(rest, n, usage):
    ops = [o.strip() for o in rest.split(",")] if rest.strip() else []
    if len(ops) != n or not all(ops):
        raise AsmError(f"usage: {usage}")
    return ops


def _encode(mnemonic, rest, labels):
    """Encode the opcode + argument bits (delay/side-set is added by the caller)."""
    m = mnemonic.lower()
    if m == "jmp":
        toks = rest.split()
        if len(toks) == 1:
            cond, target = "ALWAYS", toks[0]
        elif len(toks) == 2:
            by_syntax = {v: k for k, v in isa.JMP_COND_SYNTAX.items() if v}
            if toks[0].lower() not in by_syntax:
                raise AsmError(f"unknown jmp condition {toks[0]!r} "
                               f"(expected one of: {', '.join(by_syntax)})")
            cond, target = by_syntax[toks[0].lower()], toks[1]
        else:
            raise AsmError("usage: jmp [cond] target")
        if target in labels:
            addr = labels[target]
        elif re.match(r"^[A-Za-z_]\w*$", target):
            raise AsmError(f"undefined label {target!r}")
        else:
            addr = _ranged(target, "jump target", 0, isa.PROG_DEPTH - 1)
        return (isa.OPCODE.put(isa.OP["JMP"]) | isa.JMP_COND.put(isa.LEGAL_JMP_CONDS[cond])
                | isa.JMP_TARGET.put(addr))

    if m == "wait":
        toks = rest.split()
        if len(toks) != 3:
            raise AsmError("usage: wait POL pin|gpio|timer|flag INDEX")
        pol = _ranged(toks[0], "wait polarity", 0, 1)
        src = _select(toks[1], isa.WAIT_SRCS, "wait source")
        idx = _ranged(toks[2], "wait index", 0, (1 << isa.WAIT_IDX.width) - 1)
        return (isa.OPCODE.put(isa.OP["WAIT"]) | isa.WAIT_POL.put(pol)
                | isa.WAIT_SRC.put(src) | isa.WAIT_IDX.put(idx))

    if m in ("in", "out"):
        table, what = ((isa.LEGAL_IN_SRCS, "in source") if m == "in"
                       else (isa.LEGAL_OUT_DESTS, "out destination"))
        sel, cnt = _operands(rest, 2, f"{m} SELECTOR, COUNT")
        return (isa.OPCODE.put(isa.OP[m.upper()]) | isa.OUTIN_SEL.put(_select(sel, table, what))
                | isa.OUTIN_CNT.put(_count(cnt)))

    if m in ("push", "pull"):
        flag_word = "ifempty" if m == "pull" else "iffull"
        ifflag, block = 0, 1
        for tok in rest.lower().split():
            if tok == flag_word:
                ifflag = 1
            elif tok in ("block", "noblock"):
                block = int(tok == "block")
            else:
                raise AsmError(f"usage: {m} [{flag_word}] [block|noblock]")
        direction = isa.PP_DIR_PULL if m == "pull" else isa.PP_DIR_PUSH
        return (isa.OPCODE.put(isa.OP["PUSHPULL"]) | isa.PP_DIR.put(direction)
                | isa.PP_IFFLAG.put(ifflag) | isa.PP_BLOCK.put(block))

    if m == "set":
        dest, value = _operands(rest, 2, "set DEST, VALUE")
        return (isa.OPCODE.put(isa.OP["SET"])
                | isa.SET_DEST.put(_select(dest, isa.LEGAL_SET_DESTS, "set destination"))
                | isa.SET_IMM.put(_ranged(value, "set value", 0, 255)))

    raise AsmError(f"unknown instruction {mnemonic!r}")


def _clean(line):
    return _COMMENT_RE.sub("", line).strip()


def assemble(text, name="<string>"):
    lines = text.splitlines()

    # Pass 1: labels -> addresses.
    labels, addr = {}, 0
    for lineno, raw in enumerate(lines, 1):
        line = _clean(raw)
        m = _LABEL_RE.match(line)
        if m:
            if m.group(1) in labels:
                raise AsmError(f"{name}:{lineno}: duplicate label {m.group(1)!r}")
            labels[m.group(1)] = addr
            line = m.group(2)
        if line and not line.startswith(".side_set"):
            addr += 1

    # Pass 2: encode.
    prog = Program(words=[], labels=labels)
    for lineno, raw in enumerate(lines, 1):
        line = _clean(raw)
        m = _LABEL_RE.match(line)
        if m:
            line = m.group(2)
        if not line:
            continue
        try:
            if line.startswith(".side_set"):
                if prog.words:
                    raise AsmError(".side_set must come before the first instruction")
                prog.side_set_count = _ranged(line.split(maxsplit=1)[-1], ".side_set", 0, 2)
                continue
            prog.words.append(_assemble_line(line, labels, prog.side_set_count))
            prog.source.append(line)
        except AsmError as e:
            raise AsmError(f"{name}:{lineno}: {e}\n    {raw.strip()}") from None

    if len(prog.words) > isa.PROG_DEPTH:
        raise AsmError(f"{name}: {len(prog.words)} instructions exceed PROG_DEPTH={isa.PROG_DEPTH}")
    return prog


def _assemble_line(line, labels, side_set_count):
    delay = 0
    m = _DELAY_RE.search(line)
    if m:
        delay = _int(m.group(1), "delay")
        line = line[:m.start()].rstrip()
    side = None
    m = _SIDE_RE.search(line)
    if m:
        side = _int(m.group(1), "side-set value")
        line = line[:m.start()].rstrip()

    if line.startswith(".word"):
        if side is not None or delay:
            raise AsmError(".word takes no side-set or delay")
        word = _int(line.split(maxsplit=1)[-1], ".word")
        problems = isa.check_word(word)
        if problems:
            raise AsmError("; ".join(problems))
        return word

    mnemonic, _, rest = line.partition(" ")
    word = _encode(mnemonic, rest.strip(), labels)

    delay_bits = isa.DELAYSS.width - side_set_count
    if not 0 <= delay < (1 << delay_bits):
        raise AsmError(f"delay {delay} out of range 0-{(1 << delay_bits) - 1} "
                       f"with .side_set {side_set_count}")
    if side_set_count:
        if side is None:
            raise AsmError(f"missing `side` value (.side_set {side_set_count})")
        if not 0 <= side < (1 << side_set_count):
            raise AsmError(f"side-set value {side} does not fit in {side_set_count} bits")
        word |= isa.DELAYSS.put((side << delay_bits) | delay)
    else:
        if side is not None:
            raise AsmError("`side` used but .side_set is 0")
        word |= isa.DELAYSS.put(delay)

    assert not isa.check_word(word), isa.check_word(word)
    return word


def assemble_file(path):
    path = Path(path)
    return assemble(path.read_text(), name=path.name)


def read_hex(path):
    """Read a $readmemh image (one word per line, // comments) back into a word list."""
    words = []
    for line in Path(path).read_text().splitlines():
        line = _clean(line)
        if line:
            words.append(int(line, 16))
    return words


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("source", help="assembly file (or hex file with -d)")
    ap.add_argument("-o", "--output", help="write hex here instead of stdout")
    ap.add_argument("-d", "--disassemble", action="store_true", help="disassemble a hex file")
    ap.add_argument("--side-set", type=int, default=0, help="side-set count for -d")
    args = ap.parse_args(argv)

    if args.disassemble:
        for addr, word in enumerate(read_hex(args.source)):
            problems = isa.check_word(word)
            note = f"   ; ILLEGAL: {'; '.join(problems)}" if problems else ""
            print(f"{addr:3d}: {word:06X}  {isa.disassemble(word, args.side_set)}{note}")
        return 0

    try:
        prog = assemble_file(args.source)
    except AsmError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    out = prog.to_hex(Path(args.source).name)
    if args.output:
        Path(args.output).write_text(out)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
